server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址 lb代表负载均衡
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#          filters:
#            - AddRequestHeader=Truth,Itcast is freaking awesome! # 添加请求头
      default-filters: # 默认过滤器,对所有请求生效
        - AddRequestHeader=Truth,Itcast is freaking awesome! # 添加请求头
      globalcors: # 全局跨域处理
        add-to-simple-url-handler-mapping: true # 解决option请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins:  # 允许那些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期